project:
  type: website

website:
  title: "quarto-blog"
  site-url: https://www.myblogexample.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml 
format:
  html:
    theme: Superhero
    css: styles.css



