---
title: "Intro Post"
execute: 
  eval: true
format:
  html:
    highlight: true
    code-fold: show
    code-tools: true
    highlight-style: github
---

I originally had a blog via `Blogdown`, however, for a while I have wanted an option that was more agnostic to what language I wanted to use. Once I discovered `Quarto`, like many other people, I know that I would want to swap over. This post is not to show what great features are available with `Quarto`, instead this is more of an intro, and reminder for myself.

Instead of porting my blog, I decided that I would start from scratch so I could keep the posts that I wanted, and fix the ones that I would keep. I have learned a lot since the start of my original blog, and I thought it might be best to make note of that. Instead of removing less efficient approaches that my old posts might have, this will be a good chance to take advantage of the features that `Quarto` provide. I'll give an example in my next post.

Given how much easier it will be to post, my goal will be to have a new blog post at least once a month. From this post it will not be too much of a challenge since I have a lot of drafts saved, however, my goal is for sustainability in the future. 