---
title: "Untitled"
execute: 
  freeze: true
  eval: false
format:
  html:
    highlight: true
    code-fold: show
    code-tools: true
    highlight-style: github
---


# Gambling

    Decimal Odds -> 3.5 or 3.5:1
    Fractional Odds -> 7/2
    Moneyline Odds -> +350

### Decimal Odds Conversion to Percentage

$$\frac{1}{\text{decimal odds}}$$

`Implied probability = 1/3.5 = 0.2857...`

### Fractional Odds Conversion to Percentage

For every `2` units you bet, you get `7` back

<div>

$$\frac{\text{Denominator}}{\text{Denominator + Numerator}} \\
\text{Implied probability =}\frac{2}{(7 + 2)} = \frac{2}{9} = 0.22
$$

</div>

### Moneyline

-   `-120` means you need to bet `$120` to make a profit of `$100` (total of `$220`)
-   `+120` means you need to bet `$100` to make a profit of `$120` (total of `$220`)

#### For Negative Moneyline Odds, It's the Following:

`( – (minus moneyline odds)) + 100)`

#### Example of a Moneyline Odds of -120.

$$
\text{Implied probability} = \frac{(- (-120)}{((- (-120)) + 100)} = \frac{120}{(120 + 100)}
= \frac{120}{220} = 0.545
$$

Multiplied then by `100`, we get the implied probability percentage of `54.5%`.

Now the calculation for `+` moneyline odds, we make the following calculation:

$$
\frac{100}{\text{plus moneyline odds} + 100}
$$

#### So Let's Use Our Example of Moneyline Odds Offer of +120

$$
\frac{100}{(120 + 100)} = \frac{100}{220} = 0.4545..
$$

Multiplied then by `100`, we get the implied probability percentage of `45.45%`.

## How Do We Convert One Odds Format to Another?

### Converting Implied Probability Into Decimal Odds.

$$
\frac{100}{\text{implied probability}}
$$

#### E.g. Implied Probability of 75% Would Return Decimal Odds of 1.33.

$$
\frac{100}{75} = 1.33
$$

### Converting Implied Probability Into Fractional Odds

$$
(\frac{100}{\text{implied probability}}) - 1
$$

#### So an Example of 25% Implied Probability Would Be Calculated as:

$$
(\frac{100}{25}) - 1 = 4 - 1 = 3 \\
\text{expressed as 3 to 1}
$$

### Converting Implied Probability Into Moneyline Odds

This depends on whether the implied probability is above `50%` or below.

If it is **above**, we make the following calculation.

$$
(\frac{\text{implied probability}}{100 - \text{implied probability}}) \times 100
$$

#### So for Example, the Implied Probability of 75%.

$$
\text{Moneyline odds} = - \frac{(probability)}{(100 – probability) \times 100} \\
- (\frac{75}{100-75}) \times 100 = - (\frac{75}{25}) \times 100 = 3 \times 100 = -300
$$

If the implied probability is below `50%`, the calculation is adjusted a little.

$$
(\frac{100 - \text{implied probability}}{\text{implied probability}}) \times 100
$$

#### So for Example, the Implied Probability of 25%.

$$
\text{Moneyline odds} = \frac{(100 – probability)}{(probability)} \times 100) = (\frac{75}{25} \times 100) = 3 \times 100 = + 300
$$
